[package]
name = "example_project"       # Название вашего проекта
version = "0.1.0"              # Версия проекта
edition = "2021"               # Рекомендуемая версия Rust

[dependencies]
# Здесь можно добавлять зависимости, когда они появятся